toml-version = "v1.1.0"

[[schemas]]
path = "tombi://www.schemastore.org/cargo.json"
include = ["Cargo.toml"]

[[schemas.overrides]]
targets = [
  "dependencies",
  "dev-dependencies",
  "build-dependencies",
]

[schemas.overrides.format.rules]
table-keys-order = "ascending"
