[package]
name = "proc-macro-workshop"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]
members = ["bitfield", "builder", "debug", "seq", "sorted"]

[workspace.dependencies]
proc-macro2 = "1.0.107"
quote = "1.0.47"
seq = { path = "seq" }
sorted = { path = "sorted" }
syn = { version = "3.0.5", features = ["full"] }
thiserror = "2.0.20"
trybuild = { version = "1.0.108", features = ["diff"] }

[[bin]]
name = "workshop"
path = "main.rs"

[dependencies]
bitfield = { path = "bitfield" }
derive_builder = { path = "builder" }
derive_debug = { path = "debug" }

[profile.dev]
opt-level = 0
debug = 1
incremental = true

[profile.dev.package."*"]
opt-level = 0
