[package]
name = "derive_builder"
version = "0.0.0"
edition = "2024"
publish = false
autotests = false

[lib]
proc-macro = true

[[example]]
name = "parse"
path = "tests/01-parse.rs"

[[example]]
name = "create-builder"
path = "tests/02-create-builder.rs"

[[example]]
name = "call-setters"
path = "tests/03-call-setters.rs"

[[example]]
name = "call-build"
path = "tests/04-call-build.rs"

[[example]]
name = "method-chaining"
path = "tests/05-method-chaining.rs"

[[example]]
name = "optional-field"
path = "tests/06-optional-field.rs"

[[test]]
name = "tests"
path = "tests/progress.rs"

[dependencies]
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = { version = "3.0.5", features = ["full"] }

[dev-dependencies]
trybuild = { version = "1.0.108", features = ["diff"] }
